server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**

        - id: promo-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/promos/**
            - Method=GET,POST   # ✅ this ensures both GET & POST are forwarded

        - id: category-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/categories/**
